services:
  - type: web
    name: carrier-campaign-server
    env: python
    region: california
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /docs 
    autoDeploy: true